<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Save, ShieldCheck } from '@lucide/vue'
import { api } from '../../services/api'
import type { ApiResponse, Settings } from '../../types'

const form=reactive({shop_name:'Cái Tiệm',shop_phone:'0914.780.342',shop_address:'',shop_email:'',shipping_fee:0,is_accepting_orders:true});const loading=ref(true);const saving=ref(false);const error=ref('');const success=ref('')
onMounted(async()=>{try{const {data}=await api.get<ApiResponse<Settings>>('/admin/settings');Object.assign(form,{...data.data,shipping_fee:Number(data.data.shipping_fee||0),is_accepting_orders:data.data.is_accepting_orders!=='false'})}catch(e){error.value=e instanceof Error?e.message:'Không tải được cài đặt.'}finally{loading.value=false}})
async function save(){saving.value=true;error.value='';success.value='';try{await api.put('/admin/settings',form);success.value='Đã lưu cài đặt.'}catch(e){error.value=e instanceof Error?e.message:'Không lưu được.'}finally{saving.value=false}}
</script>
<template><section><div class="admin-page-head"><div><span class="eyebrow">Cài đặt</span><h1>Thông tin quán</h1><p>Nội dung này được hiển thị trên website và dùng khi tính đơn.</p></div></div><p v-if="error" class="admin-error">{{error}}</p><p v-if="success" class="admin-success">{{success}}</p><form class="settings-grid" @submit.prevent="save"><section class="admin-card panel"><h2 class="serif">Thông tin liên hệ</h2><label class="field-label">Tên quán<input v-model="form.shop_name" class="field" required maxlength="120"/></label><label class="field-label">Số điện thoại<input v-model="form.shop_phone" class="field" maxlength="30"/></label><label class="field-label">Địa chỉ<textarea v-model="form.shop_address" class="field" rows="3" maxlength="500"></textarea></label><label class="field-label">Email hiển thị<input v-model="form.shop_email" class="field" type="email" maxlength="254"/></label></section><section class="admin-card panel"><h2 class="serif">Nhận đơn</h2><label class="field-label">Phí giao hàng mặc định (đ)<input v-model.number="form.shipping_fee" class="field" type="number" min="0" step="1000"/></label><label class="switch-row"><div><b>Nhận đơn trên website</b><small>Khi tắt, khách vẫn xem được menu nhưng không gửi được đơn.</small></div><input v-model="form.is_accepting_orders" type="checkbox"/></label><div class="security"><ShieldCheck/><div><b>Secret được bảo vệ</b><p>SMTP, Cloudinary, Gemini và JWT chỉ cấu hình qua biến môi trường trên VPS, không lưu tại đây.</p></div></div><button class="btn btn-primary save" :disabled="saving||loading"><span v-if="saving" class="spinner"></span><Save v-else :size="18"/>{{saving?'Đang lưu...':'Lưu cài đặt'}}</button></section></form></section></template>
<style scoped>
.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.panel{padding:25px;display:grid;gap:17px;align-content:start}.panel h2{margin:0 0 5px;color:var(--coffee);font-size:1.75rem}.switch-row{display:flex;gap:20px;justify-content:space-between;align-items:center;padding:17px;border-radius:14px;background:#f1e5d7}.switch-row b,.switch-row small{display:block}.switch-row small{margin-top:4px;color:#86776d;line-height:1.4}.switch-row input{width:20px;height:20px}.security{display:flex;gap:12px;padding:16px;color:#4c6947;border:1px solid #ceddc8;border-radius:14px;background:#edf5e9}.security p{margin:4px 0 0;color:#6a7b66;font-size:.82rem;line-height:1.5}.save{width:100%}@media(max-width:750px){.settings-grid{grid-template-columns:1fr}}
</style>
