<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Pencil, Plus, Sparkles, X } from '@lucide/vue'
import { api } from '../../services/api'
import type { ApiResponse, Quote } from '../../types'

const quotes=ref<Quote[]>([]);const loading=ref(true);const error=ref('');const success=ref('');const show=ref(false);const generating=ref(false);const form=reactive({id:0,content:'',topic:'Cà phê',isActive:true});const ai=reactive({count:10,topic:'Cà phê và năng lượng tích cực'})
async function load(){loading.value=true;try{const {data}=await api.get<ApiResponse<Quote[]>>('/admin/quotes');quotes.value=data.data}catch(e){error.value=e instanceof Error?e.message:'Không tải được.'}finally{loading.value=false}}
function edit(q?:Quote){Object.assign(form,q?{id:q.id,content:q.content,topic:q.topic||'',isActive:q.isActive??true}:{id:0,content:'',topic:'Cà phê',isActive:true});show.value=true}
async function save(){try{if(form.id)await api.put(`/admin/quotes/${form.id}`,form);else await api.post('/admin/quotes',form);show.value=false;success.value='Đã lưu thông điệp.';await load()}catch(e){error.value=e instanceof Error?e.message:'Không lưu được.'}}
async function hide(q:Quote){try{await api.delete(`/admin/quotes/${q.id}`);await load()}catch(e){error.value=e instanceof Error?e.message:'Không ẩn được.'}}
async function generate(){generating.value=true;error.value='';try{const {data}=await api.post<ApiResponse<Quote[]>>('/admin/quotes/generate-ai',ai);success.value=data.message||'Đã tạo thông điệp.';await load()}catch(e){error.value=e instanceof Error?e.message:'Không tạo được.'}finally{generating.value=false}}
onMounted(load)
</script>
<template><section><div class="admin-page-head"><div><span class="eyebrow">Vibe QR</span><h1>Thông điệp tích cực</h1><p>Một QR tĩnh, mỗi lượt ghé là một lời nhắn ngẫu nhiên.</p></div><button class="btn btn-primary" @click="edit()"><Plus :size="18"/>Thêm câu</button></div><p v-if="error" class="admin-error">{{error}}</p><p v-if="success" class="admin-success">{{success}}</p><section class="ai-box admin-card"><div class="ai-icon"><Sparkles/></div><div><h2 class="serif">Tạo nhanh bằng Gemini</h2><p>AI chỉ thêm câu mới; nội dung trùng sẽ được bỏ qua.</p></div><input v-model="ai.topic" class="field" aria-label="Chủ đề"/><input v-model.number="ai.count" class="field count" type="number" min="1" max="20" aria-label="Số lượng"/><button class="btn btn-primary" :disabled="generating" @click="generate"><span v-if="generating" class="spinner"></span>{{generating?'Đang tạo...':'Tạo thông điệp'}}</button></section><div class="quote-grid"><article v-for="quote in quotes" :key="quote.id" class="admin-card quote"><span class="topic">{{quote.topic||'Thông điệp'}}</span><blockquote class="serif">“{{quote.content}}”</blockquote><div><small>{{quote.scanCount||0}} lượt</small><span :class="['pill',quote.isActive?'green':'red']">{{quote.isActive?'Đang dùng':'Đã ẩn'}}</span><button @click="edit(quote)"><Pencil :size="15"/>Sửa</button><button v-if="quote.isActive" @click="hide(quote)">Ẩn</button></div></article></div><div v-if="loading" class="admin-empty">Đang tải thông điệp...</div><div v-else-if="!quotes.length" class="admin-empty">Chưa có thông điệp.</div>
  <div v-if="show" class="admin-modal" @click.self="show=false"><form class="admin-modal-box" @submit.prevent="save"><button type="button" class="admin-modal-close" @click="show=false"><X/></button><h2>{{form.id?'Sửa thông điệp':'Thêm thông điệp'}}</h2><label class="field-label">Nội dung<textarea v-model="form.content" class="field" required minlength="10" maxlength="500" rows="6"></textarea></label><label class="field-label topic-field">Chủ đề<input v-model="form.topic" class="field" maxlength="100"/></label><label class="check"><input v-model="form.isActive" type="checkbox"/> Đang sử dụng</label><button class="btn btn-primary save">Lưu thông điệp</button></form></div>
</section></template>
<style scoped>
.ai-box{padding:20px;display:grid;grid-template-columns:55px minmax(180px,.8fr) 1fr 85px auto;gap:14px;align-items:center;margin-bottom:22px}.ai-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:50%;color:#9a5d37;background:#f0ddc6}.ai-box h2{margin:0;color:var(--coffee);font-size:1.45rem}.ai-box p{margin:3px 0;color:#8a7b70;font-size:.8rem}.quote-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.quote{padding:22px}.topic{color:#a36843;text-transform:uppercase;letter-spacing:.12em;font-size:.66rem;font-weight:800}.quote blockquote{margin:15px 0 22px;color:var(--coffee);font-size:1.35rem;line-height:1.45}.quote>div{display:flex;align-items:center;gap:10px}.quote small{margin-right:auto;color:#8c7d73}.quote button{display:flex;gap:4px;align-items:center;border:0;background:transparent;color:#905534;font-weight:700}.topic-field,.check{margin-top:15px}.check{display:flex;gap:7px}.save{width:100%;margin-top:20px}@media(max-width:1050px){.ai-box{grid-template-columns:55px 1fr}.ai-box .field,.ai-box .btn{grid-column:2}.count{width:100%}}@media(max-width:650px){.quote-grid{grid-template-columns:1fr}.ai-box{grid-template-columns:1fr}.ai-box .field,.ai-box .btn{grid-column:1}.admin-page-head{align-items:flex-start;flex-direction:column}}
</style>
