<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowDown, ArrowRight, Clock3, Coffee, Heart, MapPin, Phone, ShoppingBag, Sparkles } from '@lucide/vue'
import SiteHeader from '../components/SiteHeader.vue'
import ProductModal from '../components/ProductModal.vue'
import CartDrawer from '../components/CartDrawer.vue'
import { api } from '../services/api'
import type { ApiResponse, Category, Product, Settings } from '../types'

const categories = ref<Category[]>([]); const products = ref<Product[]>([]); const settings = ref<Settings>({ shipping_fee: '0', shop_name: 'Cái Tiệm', shop_phone: '0914.780.342', is_accepting_orders: 'true' })
const activeCategory = ref<number | 'all'>('all'); const selected = ref<Product | null>(null); const loading = ref(true); const error = ref('')
const filtered = computed(() => activeCategory.value === 'all' ? products.value : products.value.filter((product) => product.categoryId === activeCategory.value))
const money = (value: string | number) => new Intl.NumberFormat('vi-VN').format(Number(value)) + 'đ'

async function load() {
  loading.value = true; error.value = ''
  try {
    const [categoryRes, productRes, settingRes] = await Promise.all([api.get<ApiResponse<Category[]>>('/categories'), api.get<ApiResponse<Product[]>>('/products'), api.get<ApiResponse<Settings>>('/settings/public')])
    categories.value = categoryRes.data.data; products.value = productRes.data.data; settings.value = { ...settings.value, ...settingRes.data.data }
  } catch (err) { error.value = err instanceof Error ? err.message : 'Không tải được menu.' }
  finally { loading.value = false }
}
onMounted(load)
</script>

<template>
  <main>
    <SiteHeader />
    <section class="hero">
      <div class="hero-overlay"></div><div class="hero-glow"></div>
      <div class="container hero-content fade-rise"><span class="hero-tag"><Coffee :size="15" /> Một góc nhỏ, một vị quen</span><h1 class="serif">Một chút cà phê.<br /><em>Một ngày thật chill.</em></h1><p>Những món quen được pha thật chỉn chu, giao tận nơi để ngày của bạn bắt đầu nhẹ nhàng hơn.</p><div class="hero-actions"><a href="#menu" class="btn btn-light">Xem menu <ArrowDown :size="18" /></a><RouterLink to="/vibe" class="btn hero-vibe"><Sparkles :size="17" /> Rút một lời nhắn</RouterLink></div></div>
      <div class="hero-note"><span>Phục vụ mỗi ngày</span><b>Cà phê • Ca cao • Sữa chua</b></div>
    </section>

    <section class="quick-info"><div class="container info-grid"><article><span><Clock3 /></span><div><b>Món quen, pha mới</b><small>Chuẩn bị khi bạn đặt</small></div></article><article><span><ShoppingBag /></span><div><b>Đặt món thật gọn</b><small>Không cần tài khoản</small></div></article><article><span><Heart /></span><div><b>Một chút dễ thương</b><small>Quét QR nhận lời nhắn</small></div></article></div></section>

    <section id="menu" class="menu-section">
      <div class="container"><div class="section-head"><div><span class="eyebrow">Menu của quán</span><h2 class="serif">Hôm nay bạn uống gì?</h2></div><p>Chọn một món quen, thêm ghi chú nếu cần. Còn lại để Cái Tiệm chuẩn bị.</p></div>
        <div class="category-tabs"><button :class="{ active: activeCategory === 'all' }" @click="activeCategory = 'all'">Tất cả</button><button v-for="category in categories" :key="category.id" :class="{ active: activeCategory === category.id }" @click="activeCategory = category.id">{{ category.name }}</button></div>
        <div v-if="loading" class="state"><span class="spinner"></span><p>Đang mở menu...</p></div>
        <div v-else-if="error" class="state error-state"><p>{{ error }}</p><button class="btn btn-outline" @click="load">Thử lại</button></div>
        <div v-else-if="!filtered.length" class="state"><p>Danh mục này chưa có món.</p></div>
        <div v-else class="product-grid">
          <article v-for="(product, index) in filtered" :key="product.id" class="product-card" :style="{ '--delay': `${Math.min(index, 8) * 55}ms` }"><div class="product-image"><img :src="product.imageUrl || '/images/menu/coffee.webp'" :alt="product.name" loading="lazy" /><span v-if="product.isOutOfStock">Hết hàng</span></div><div class="product-copy"><small>{{ product.category?.name }}</small><h3 class="serif">{{ product.name }}</h3><p>{{ product.description || 'Một món quen, pha mới khi bạn đặt.' }}</p><div><strong>{{ money(product.price) }}</strong><button :disabled="product.isOutOfStock" :aria-label="`Thêm ${product.name}`" @click="selected = product"><span>{{ product.isOutOfStock ? 'Tạm hết' : 'Chọn món' }}</span><ArrowRight :size="17" /></button></div></div></article>
        </div>
      </div>
    </section>

    <section id="story" class="story"><div class="story-image"><img src="/images/brand/hero-cafe.webp" alt="Không gian ấm áp tại Cái Tiệm" loading="lazy" /></div><div class="story-copy"><span class="eyebrow">Câu chuyện nhỏ</span><h2 class="serif">Không cần cầu kỳ,<br /><em>chỉ cần vừa ý.</em></h2><p>Cái Tiệm là một góc nhỏ dành cho những ly nước quen thuộc và những phút nghỉ thật nhẹ. Menu gọn, giá dễ thương, đặt món nhanh — đúng tinh thần của một quán gần nhà.</p><div class="story-stats"><div><b>4</b><span>nhóm thức uống</span></div><div><b>1</b><span>QR đầy năng lượng</span></div><div><b>0</b><span>bước đăng nhập</span></div></div><RouterLink to="/vibe" class="text-link">Nhận một thông điệp hôm nay <ArrowRight :size="18" /></RouterLink></div></section>

    <section class="vibe-banner"><div class="container"><div class="vibe-icon"><Sparkles /></div><div><span class="eyebrow">Vibe từ Cái Tiệm</span><h2 class="serif">Một lời nhắn nhỏ,<br />đúng lúc bạn cần.</h2></div><p>Mỗi lần ghé là một câu khác. Không hứa giải quyết mọi chuyện — chỉ mong ngày của bạn dịu hơn một chút.</p><RouterLink to="/vibe" class="btn btn-light">Rút một lời nhắn <ArrowRight :size="18" /></RouterLink></div></section>

    <footer id="contact"><div class="container footer-grid"><div class="footer-brand"><img src="/images/brand/cafe-name.png" alt="Cái Tiệm" /><p>Một chút cà phê. Một ngày thật chill.</p></div><div><b>Liên hệ</b><a v-if="settings.shop_phone" :href="`tel:${settings.shop_phone}`"><Phone :size="17" />{{ settings.shop_phone }}</a><span v-if="settings.shop_address"><MapPin :size="17" />{{ settings.shop_address }}</span><span v-else><MapPin :size="17" />Địa chỉ sẽ được cập nhật</span></div><div><b>Khám phá</b><a href="#menu">Menu</a><RouterLink to="/vibe">Vibe QR</RouterLink><RouterLink to="/admin/login">Quản trị</RouterLink></div></div><div class="container footer-bottom"><span>© {{ new Date().getFullYear() }} Cái Tiệm</span><span>Làm bằng một chút cà phê và rất nhiều chân thành.</span></div></footer>

    <ProductModal :product="selected" @close="selected = null" /><CartDrawer :settings="settings" />
  </main>
</template>

<style scoped>
.hero { position: relative; min-height: 820px; display: flex; align-items: center; color: white; overflow: hidden; background: #1e130e url('/images/brand/hero-cafe.webp') center/cover no-repeat; }
.hero-overlay { position: absolute; inset: 0; background: linear-gradient(90deg, rgba(24,13,8,.9) 0%, rgba(30,17,10,.7) 45%, rgba(25,14,9,.1) 78%), linear-gradient(0deg, rgba(25,14,9,.55), transparent 45%); }.hero-glow { position: absolute; width: 600px; height: 600px; left: -280px; bottom: -340px; border-radius: 50%; background: #c58b55; filter: blur(120px); opacity: .2; }
.hero-content { position: relative; z-index: 2; padding-top: 50px; }.hero-tag { display: inline-flex; gap: 8px; align-items: center; padding: 8px 13px; border: 1px solid rgba(255,255,255,.22); border-radius: 999px; background: rgba(255,255,255,.08); backdrop-filter: blur(8px); text-transform: uppercase; letter-spacing: .12em; font-size: .68rem; font-weight: 700; }.hero h1 { max-width: 800px; margin: 22px 0; font-size: clamp(3.5rem, 7.5vw, 6.8rem); line-height: .98; letter-spacing: -.045em; }.hero h1 em { color: #efbd84; font-weight: 600; }.hero-content > p { max-width: 540px; color: rgba(255,255,255,.78); font-size: 1.08rem; line-height: 1.75; }.hero-actions { display: flex; gap: 12px; margin-top: 34px; }.hero-vibe { color: white; border: 1px solid rgba(255,255,255,.24); background: rgba(255,255,255,.08); backdrop-filter: blur(8px); }.hero-note { position: absolute; z-index: 2; right: 4vw; bottom: 35px; display: grid; gap: 4px; padding-left: 20px; border-left: 1px solid rgba(255,255,255,.4); font-size: .83rem; }.hero-note span { color: #deb991; }
.quick-info { position: relative; z-index: 4; margin-top: -35px; }.info-grid { display: grid; grid-template-columns: repeat(3,1fr); overflow: hidden; border-radius: 22px; background: var(--paper); box-shadow: var(--shadow); }.info-grid article { display: flex; align-items: center; gap: 15px; padding: 25px 28px; }.info-grid article + article { border-left: 1px solid rgba(59,36,23,.09); }.info-grid article > span { width: 43px; height: 43px; display: grid; place-items: center; border-radius: 50%; color: var(--coffee); background: #edddca; }.info-grid b,.info-grid small { display: block; }.info-grid small { margin-top: 3px; color: #6f6158; }
.menu-section { padding: 120px 0 130px; background: radial-gradient(circle at 90% 20%, rgba(197,139,85,.12), transparent 28%), var(--cream); }.section-head { display: flex; justify-content: space-between; align-items: end; gap: 40px; }.section-head h2 { margin: 12px 0 0; color: var(--coffee); font-size: clamp(2.7rem, 5vw, 4.7rem); letter-spacing: -.035em; }.section-head > p { max-width: 380px; margin-bottom: 10px; color: #75675e; line-height: 1.7; }.category-tabs { display: flex; gap: 8px; margin: 38px 0 32px; overflow-x: auto; padding-bottom: 5px; }.category-tabs button { flex: 0 0 auto; border: 1px solid rgba(59,36,23,.12); border-radius: 99px; padding: 10px 18px; background: transparent; color: #64544a; font-weight: 600; }.category-tabs button.active { border-color: var(--coffee); background: var(--coffee); color: white; }.product-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 22px; }.product-card { overflow: hidden; border-radius: 25px; background: rgba(255,250,243,.9); border: 1px solid rgba(59,36,23,.08); transition: .3s ease; animation: rise .5s var(--delay) both; }.product-card:hover { transform: translateY(-7px); box-shadow: var(--shadow); }.product-image { position: relative; aspect-ratio: 1.22; overflow: hidden; }.product-image img { width: 100%; height: 100%; object-fit: cover; transition: .5s; }.product-card:hover img { transform: scale(1.035); }.product-image span { position: absolute; inset: 0; display: grid; place-items: center; background: rgba(35,23,16,.65); color: white; font-weight: 700; }.product-copy { padding: 23px; }.product-copy small { color: var(--caramel); text-transform: uppercase; letter-spacing: .12em; font-size: .66rem; font-weight: 700; }.product-copy h3 { margin: 7px 0; font-size: 1.55rem; color: var(--coffee); }.product-copy p { height: 42px; color: #807168; line-height: 1.45; font-size: .87rem; }.product-copy > div { display: flex; align-items: center; justify-content: space-between; }.product-copy strong { font-size: 1.05rem; color: #a45f2e; }.product-copy button { display: flex; align-items: center; gap: 7px; border: 0; background: transparent; color: var(--coffee); font-weight: 700; }.product-copy button:disabled { color: #9f9288; }.state { min-height: 260px; display: grid; gap: 12px; place-items: center; align-content: center; color: #75675e; }.error-state { color: #9d2d26; }
.story { display: grid; grid-template-columns: 1.1fr .9fr; min-height: 680px; background: var(--paper); }.story-image { overflow: hidden; }.story-image img { width: 100%; height: 100%; object-fit: cover; object-position: 62% center; }.story-copy { padding: 90px clamp(40px,7vw,110px); display: grid; align-content: center; }.story-copy .eyebrow { color: #8f522f; }.story-copy h2 { margin: 15px 0 22px; color: var(--coffee); font-size: clamp(2.7rem,5vw,4.7rem); line-height: 1.05; }.story-copy h2 em { color: #92532d; }.story-copy > p { max-width: 600px; color: #6d5f56; line-height: 1.8; }.story-stats { display: flex; gap: 38px; margin: 28px 0; padding: 24px 0; border-block: 1px solid rgba(59,36,23,.1); }.story-stats div { display: grid; }.story-stats b { color: var(--coffee); font: 700 2rem 'Playfair Display'; }.story-stats span { color: #6e6057; font-size: .78rem; }.text-link { display: inline-flex; align-items: center; gap: 8px; color: #874a27; font-weight: 700; }
.vibe-banner { padding: 90px 0; color: white; background: var(--coffee); }.vibe-banner .container { display: grid; grid-template-columns: 90px 1.1fr 1fr auto; gap: 40px; align-items: center; }.vibe-icon { width: 78px; height: 78px; display: grid; place-items: center; border: 1px solid rgba(255,255,255,.2); border-radius: 50%; color: #efbd84; background: rgba(255,255,255,.06); }.vibe-banner h2 { margin: 12px 0 0; font-size: clamp(2.2rem,4vw,3.8rem); line-height: 1.08; }.vibe-banner p { margin: 0; color: rgba(255,255,255,.7); line-height: 1.7; }
footer { padding: 72px 0 28px; color: #eadfd4; background: #1c110c; }.footer-grid { display: grid; grid-template-columns: 1.5fr 1fr .7fr; gap: 60px; }.footer-brand img { width: 190px; padding: 8px; border-radius: 8px; background: var(--paper); }.footer-brand p { margin-top: 18px; color: #b9aaa0; }.footer-grid > div:not(:first-child) { display: flex; flex-direction: column; align-items: flex-start; gap: 13px; }.footer-grid b { margin-bottom: 6px; color: #efbd84; }.footer-grid a,.footer-grid span { display: flex; gap: 9px; align-items: flex-start; color: #c3b5ab; }.footer-grid a:hover { color: white; }.footer-bottom { display: flex; justify-content: space-between; margin-top: 55px; padding-top: 20px; border-top: 1px solid rgba(255,255,255,.09); color: #aa9b91; font-size: .77rem; }
@media (max-width: 960px) { .hero { min-height: 730px; }.product-grid { grid-template-columns: repeat(2,1fr); }.story { grid-template-columns: 1fr; }.story-image { height: 430px; }.vibe-banner .container { grid-template-columns: 70px 1fr; }.vibe-banner p,.vibe-banner .btn { grid-column: 2; justify-self: start; }.footer-grid { grid-template-columns: 1fr 1fr; }.footer-brand { grid-column: 1/-1; } }
@media (max-width: 680px) { .hero { min-height: 720px; align-items: flex-end; padding-bottom: 100px; background-position: 61% center; }.hero-overlay { background: linear-gradient(0deg, rgba(24,13,8,.95) 0%, rgba(24,13,8,.58) 66%, rgba(24,13,8,.28)); }.hero h1 { font-size: 3.45rem; }.hero-note { display: none; }.hero-actions { align-items: stretch; flex-direction: column; width: 230px; }.quick-info { margin-top: 0; }.info-grid { width: 100%; border-radius: 0; grid-template-columns: 1fr; }.info-grid article + article { border-left: 0; border-top: 1px solid rgba(59,36,23,.08); }.menu-section { padding: 85px 0; }.section-head { align-items: start; flex-direction: column; gap: 8px; }.product-grid { grid-template-columns: 1fr; }.product-image { aspect-ratio: 1.5; }.story-image { height: 320px; }.story-copy { padding: 70px 24px; }.story-stats { gap: 20px; flex-wrap: wrap; }.vibe-banner .container { grid-template-columns: 1fr; }.vibe-banner p,.vibe-banner .btn { grid-column: 1; }.footer-grid { grid-template-columns: 1fr; gap: 35px; }.footer-brand { grid-column: auto; }.footer-bottom { gap: 12px; flex-direction: column; } }
</style>
